### ISSUE TITLE
GetDriverConfigInfo Function correct Capitalisation

### ISSUE THREAD

**Issue by AndrewLuecke** [control4/docs-driverworks-api#4]
**Summary:** 
https://control4.github.io/docs-driverworks-api/#getdriverconfiginfo has the incorrect function name. 

**Expected Info:**
Incorrect function name listed is: C4:GetDriverConfiginfo()

**Should be:**
Correct Function Name should be: C4:GetDriverConfigInfo() . Note the Correct Capitalisation of the I

Thanks

**Comment by jmcgeeverC4** [comment]
Andrew,
I'm back from PTO and have corrected the typo. You can see the corrected online version now. Thank you for the feedback on the docs!

Jim
